import Vue from "vue";
import AppLayout from "@/layouts/AppLayout";
import AppNotifications from "@/common/components/AppNotifications";
import AppDrag from "@/common/components/AppDrag";
import AppDrop from "@/common/components/AppDrop";
import AppButton from "@/common/components/AppButton";
import AppInput from "@/common/components/AppInput";
import ItemCounter from "@/common/components/ItemCounter";
import Logo from "@/common/components/Logo";
import RadioButton from "@/common/components/RadioButton";
import SelectorItem from "@/common/components/SelectorItem";
import UserPicture from "@/common/components/UserPicture";
import PopupLayout from "@/common/components/PopupLayout";
import PopupOverlay from "@/common/components/PopupOverlay";
import PopupButton from "@/common/components/PopupButton";
import ConfirmPopup from "@/common/components/ConfirmPopup";
import Product from "@/common/components/Product";
import PopupTransition from "@/common/components/PopupTransition";
import SlideTransitionGroup from "@/common/components/SlideTransitionGroup";

Vue.component("AppLayout", AppLayout);
Vue.component("AppNotifications", AppNotifications);
Vue.component("AppDrag", AppDrag);
Vue.component("AppDrop", AppDrop);
Vue.component("AppButton", AppButton);
Vue.component("AppInput", AppInput);
Vue.component("ItemCounter", ItemCounter);
Vue.component("Logo", Logo);
Vue.component("RadioButton", RadioButton);
Vue.component("SelectorItem", SelectorItem);
Vue.component("UserPicture", UserPicture);
Vue.component("PopupLayout", PopupLayout);
Vue.component("PopupOverlay", PopupOverlay);
Vue.component("PopupButton", PopupButton);
Vue.component("ConfirmPopup", ConfirmPopup);
Vue.component("Product", Product);
Vue.component("PopupTransition", PopupTransition);
Vue.component("SlideTransitionGroup", SlideTransitionGroup);
