export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

// Builder
export const SET_PIZZA_ENTITY = "SET_PIZZA_ENTITY";
export const UPDATE_PIZZA_INGREDIENTS = "UPDATE_PIZZA_INGREDIENTS";
export const SET_PIZZA = "SET_PIZZA";
export const RESET_PIZZA = "RESET_PIZZA";

// Cart
export const ADD_PIZZA = "ADD_PIZZA";
export const UPDATE_PIZZA = "UPDATE_PIZZA";
export const DELETE_PIZZA = "DELETE_PIZZA";
export const UPDATE_CART_ORDER_MISC = "UPDATE_CART_ORDER_MISC";
export const RESET_CART = "RESET_CART";
export const SET_CART_ENTITY = "SET_CART_ENTITY";
export const SET_ADDRESS = "SET_ADDRESS";
export const RESET_ADDRESS = "RESET_ADDRESS";
