export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

// Builder
export const SET_BUILDER_ENTITY = "SET_BUILDER_ENTITY";
export const SET_BUILDER_PIZZA_ENTITY = "SET_BUILDER_PIZZA_ENTITY";
export const ADD_BUILDER_PIZZA_INGREDIENT = "ADD_BUILDER_PIZZA_INGREDIENT";
export const REMOVE_BUILDER_PIZZA_INGREDIENT =
  "REMOVE_BUILDER_PIZZA_INGREDIENT";
export const RESET_BUILDER_PIZZA = "RESET_BUILDER_PIZZA";

// Cart
export const SET_CART_ENTITY = "SET_CART_ENTITY";
export const SET_CART_ORDER_ENTITY = "SET_CART_ORDER_ENTITY";
export const SET_CART_ORDER_ADDRESS_ENTITY = "SET_CART_ORDER_ADDRESS_ENTITY";
export const ADD_PIZZA = "ADD_PIZZA";
export const UPDATE_PIZZA = "UPDATE_PIZZA";
export const UPDATE_PIZZA_QUANTITY = "UPDATE_PIZZA_QUANTITY";
export const DELETE_PIZZA = "DELETE_PIZZA";
export const UPDATE_CART_ORDER_MISC = "UPDATE_CART_ORDER_MISC";
export const RESET_CART = "RESET_CART";
export const SET_CART_WITH_ORDER = "SET_CART_WITH_ORDER";
